# Generated by Django 5.2.1 on 2025-06-09 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('country_code', models.CharField(default='+1', max_length=5)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('budget', models.CharField(choices=[('under-10k', 'Under $10,000'), ('10k-25k', '$10,000 - $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k-250k', '$100,000 - $250,000'), ('250k-500k', '$250,000 - $500,000'), ('500k-plus', '$500,000+')], max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('region', models.CharField(choices=[('north-america', 'North America'), ('south-america', 'South America'), ('europe', 'Europe'), ('asia-pacific', 'Asia Pacific'), ('middle-east', 'Middle East'), ('africa', 'Africa'), ('oceania', 'Oceania')], max_length=20)),
                ('services', models.JSONField(default=list)),
                ('project_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('is_leadership', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'first_name'],
            },
        ),
    ]
